apiVersion: v1
kind: Pod
metadata:
  name: ambassador-app
spec:
  containers:
  - name: main-app
    image: jaimesalas/curl
    resources: {}
    command: ["sleep", "3600"]
  - name: ambassador
    image: jaimesalas/nginx-ambassador
    resources: {}
