apiVersion: v1
kind: Pod
metadata:
  name: external-app
  labels:
    app: ambassador
spec:
  containers:
  - name: nginx-outside
    image: jaimesalas/nginx-outside
    resources: {}
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lc-ambassador
spec:
  selector:
    app: ambassador
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

