secret:
  mongodb_uri:
    username: your_db_username
    password: your_db_password
    dbchart: database
    dbport: 27017
    dbconn: "tododb?authSource=admin"
  # mongodb://admin:password@mongodb:27017/tododb?authSource=admin
image:
  repository: jaimesalas/todo-app-api
  tag: "0.1.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  host: backend.minikube.local
