apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-clusterip
  name: nginx-clusterip
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  type: ClusterIP
