apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: nginx-standalone
  name: nginx-standalone
spec:
  containers:
  - image: nginx:alpine
    name: nginx-standalone
    resources:
      limits:
        cpu: "250m"
        memory: "10Mi"
