apiVersion: v1
kind: Service
metadata:
  name: single-greeting-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: single-greeting
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: single-greeting
  labels:
    app: single-greeting
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: single-greeting
  template:
    metadata:
      labels:
        app: single-greeting
    spec:
      containers:
        - name: hello-app-ctr
          image: gcr.io/google-samples/hello-app:1.0
