
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    echo "172.16.94.10 c1-cp1" >> /etc/hosts
    echo "172.16.94.11 c1-node1" >> /etc/hosts
    echo "172.16.94.12 c1-node2" >> /etc/hosts
    echo "172.16.94.13 c1-node3" >> /etc/hosts
  SHELL

  config.vm.define "c1-cp1" do |controlp|
    controlp.vm.box = "bento/ubuntu-18.04"
    controlp.vm.hostname = "c1-cp1"
    controlp.vm.network "private_network", ip: "172.16.94.10"
    controlp.vm.provider "virtualbox" do |vb|
      vb.memory = 4048
      vb.cpus = 2
    end
  end

  (1..3).each do |i|
    config.vm.define "c1-node#{i}" do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.hostname = "c1-node#{i}"
      node.vm.network "private_network", ip: "172.16.94.1#{i}"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 1
      end
    end
  end
end
