apiVersion: v1
kind: Pod
metadata:
  name: nginx-standalone
  labels:
    name: nginx-standalone
spec:
  containers:
  - name: nginx-standalone
    image: nginx:alpine
    ports:
      - containerPort: 80
    resources: {}
