apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: web-ctr
    image: jaimesalas/nginx-adapter
    resources: {}
    ports:
      - containerPort: 80
  - name: transformer
    image: nginx/nginx-prometheus-exporter
    resources: {}
    args: ["-nginx.scrape-uri", "http://localhost/nginx_status"]
    ports:
    - containerPort: 9113

