apiVersion: v1
kind: Service
metadata:
  name: terminal-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-app
spec:
  selector:
  template:
    spec:
      containers:
        - env:
            - name: PORT
              value: "3000"
          image: jaimesalas/terminal-service:0.0.2
          name: app
          resources: {}
