apiVersion: v1
kind: PersistentVolume
metadata:
  name: lc-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lc-fast  
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/lc-vol

