apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  volumes:
    - name: fast10m
      persistentVolumeClaim:
        claimName: lc-pvc
  containers:
  - name: ctr1
    image: ubuntu:latest
    command:
      - /bin/bash
      - "-c"
      - "sleep 60m"
    resources: {}
    volumeMounts:
      - mountPath: /data
        name: fast10m
