apiVersion: v1
kind: PersistentVolume
metadata:
  name: ps-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/ps-vol

