apiVersion: v1
kind: Pod
metadata:
  name: curl-ambassador
spec: 
  serviceAccountName: service-reader
  containers:
  - name: main
    image: jaimesalas/alpine-curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: jaimesalas/ambassador-alpine