backend:
  # enabled: true
  secret:
    mongodb_uri:
      username: admin
      password: password
  ingress:
    enabled: false

# database:
#   enbaled: true

tags:
  api: true

frontend:
  ingress:
    enabled: true

ingress:
  hosts:
    - host:
        domain: frontend.minikube.local
        chart: frontend
    - host:
        domain: backend.minikube.local
        chart: backend
