apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.network/todo-network: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: todo-app-backend:0.0.1
          name: todo-app-backend
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
