apiVersion: v1
kind: PersistentVolume
metadata:
  name: deployment-lc-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: lc-fast
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/deployment-lc-vol

