apiVersion: v2
name: todos
appVersion: "2.0"
description: A Helm chart for Todos Awesome App 1.1
version: 1.1.0
type: application
dependencies:
  - name: backend
    version: ~0.1.0
    repository: http://localhost:8080
  - name: frontend
    version: ^1.1.0
    repository: http://localhost:8080
  - name: database
    version: ~0.1.0
    repository: http://localhost:8080