apiVersion: v1
kind: Service
metadata:
  name: nginx-blue-test
  labels:
    app: nginx
    role: blue-test 
    env: test
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: blue 
  ports:
  - port: 9000
    targetPort: 80

