apiVersion: v1
kind: Service
metadata:
  name: nginx-green-test
  labels:
    app: nginx
    role: green-test 
    env: test
spec:
  type: LoadBalancer
  selector:
    app: nginx
    role: green 
  ports:
  - port: 9001
    targetPort: 80

