apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
data:
  # mongodb-uri: {{ .Values.secret.mongodb_uri }}
  mongodb-uri: {{ with .Values.secret.mongodb_uri -}}
  {{- list "mongodb://" .username ":" .password "@" $.Release.Name "-" .dbchart ":" .port "/" .dbconn | join "" | b64enc | quote }}
               {{- end}}
