apiVersion: v1
kind: Pod
metadata:
  name: life-hooks
  labels:
    name: life-hooks
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle:
     postStart:
        exec:
          command: ["/bin/sh", "-c", "touch /lifecycle/message"]
     preStop:
        exec:
           command: ["/bin/bash", "-c", "touch /lifecycle/mark && sleep 2 && echo preStop > /lifecycle/mark"]
    command: ["/bin/sh", "-c", "sleep 300 && echo terminating > /lifecycle/message"]
    resources: {}
    volumeMounts:
    - name: test-dir
      mountPath: /lifecycle
  # terminationGracePeriodSeconds: 120
  restartPolicy: Never
  volumes:
  - name: test-dir
    hostPath:
     path: /data
     type: Directory

# If we run `kubectl delete pod life-hooks` when `lifecycle-demo-container` is terminated
# prePost hook never happen, becuase is Kubelet who must terminate the container

# Since we're running this on minikube we can access the data by running `minikube ssh` and cd `data`
