apiVersion: v1
kind: Pod
metadata:
  name: pre-stop
  labels:
    name: pre-stop
spec:
  containers:
  - name: pre-stop
    image: jaimesalas/random-employee
    imagePullPolicy: Always
    resources: {}
    lifecycle:
      preStop:
        httpGet:
          port: 3000
          path: /shutdown
  terminationGracePeriodSeconds: 120
