apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec: 
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine:3.3"
        command: [
          /bin/sh,
          -c,
          "echo 'I run after install'"
        ]