apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-2"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-2"
    spec: 
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "alpine:3.3"
        command: [
          /bin/sh,
          -c,
          "echo 'I run after install, Am I second'; date +%s"
        ]