apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: db-passwordd
                  name: lc-secret
