apiVersion: v1
kind: Pod
metadata:
  name: ambassador-app
spec:
  containers:
  - name: main-app
    image: jaimesalas/nginx-curl
    imagePullPolicy: Always
    resources: {}
    # command: ["sleep", "3600"]
  - name: ambassador
    image: jaimesalas/nginx-ambassador
    imagePullPolicy: Always
    resources: {}
