secret:
  mongodb_uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvZGI6MjcwMTcvdG9kb2RiP2F1dGhTb3VyY2U9YWRtaW4K
  # mongodb://admin:password@mongodb:27017/tododb?authSource=admin
image:
  repository: jaimesalas/todo-app-api
  tag: "0.1.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  host: backend.minikube.local
