apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-htmlvol
spec:
  storageClassName: "host-first-consumer"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: sc-pod
  labels:
    app: stg
spec:
  volumes:
    - name: htmlvol
      persistentVolumeClaim:
        claimName: pvc-htmlvol
  containers:
  - name: main-ctr
    image: nginx
    imagePullPolicy: Always
    resources: {}
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: htmlvol
  - name: helper-ctr
    image: ubuntu
    imagePullPolicy: Always
    resources: {}
    command:
    - /bin/bash
    - "-c"
    - "sleep 60m"
    volumeMounts:
      - mountPath: /data
        name: htmlvol
---
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: stg
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

