apiVersion: v1
kind: Pod
metadata:
  labels:
    name: nginx
    rel: stable
  name: nginx
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2
      periodSeconds: 5
      failureThreshold: 1
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5
      failureThreshold: 1
