apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules.yml: |-
    # Rules

  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: file-node-exporter
        file_sd_configs:
          - files: 
            - targets.yml

  targets.yml: |-
    - labels:
        job: file-node-exporter
      targets:
        - 10.0.0.13:9100
