apiVersion: v1
kind: ConfigMap
metadata:
  # name: frontend-config
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  # todo-title: "Default"
  todo-title: {{ .Values.config.todo_title}}
  # backend-uri: "backend.minikube.local"
  backend-uri: {{ .Values.config.backend_uri }}
  cors: "true"
